In [1]:
import numpy as np
import cv2

In [51]:
driveName = r"\\.\PhysicalDrive1"  # Change this to the correct drive

# SD Card sector information
headerSector =          1023 # Holds user settings to configure Miniscope and recording
configSector =          1024 # Holds final settings of the actual recording
dataStartSector =       1025 # Recording data starts here
sectorSize =            512

WRITE_KEY0 =				0x0D7CBA17
WRITE_KEY1 =				0x0D7CBA17
WRITE_KEY2 =				0x0D7CBA17
WRITE_KEY3 =				0x0D7CBA17

# SD Card Header Sector positions
HEADER_GAIN_POS =				4
HEADER_LED_POS =				5
HEADER_EWL_POS =				6
HEADER_RECORD_LENGTH_POS =  	7
HEADER_FRAME_RATE = 			8

# SD Card Config Sector positions
CONFIG_BLOCK_WIDTH_POS =			0
CONFIG_BLOCK_HEIGHT_POS	=   		1
CONFIG_BLOCK_FRAME_RATE_POS	=   	2
CONFIG_BLOCK_BUFFER_SIZE_POS =  	3

# Data Buffer Header positions
BUFFER_HEADER_BUFFER_LENGTH_POS =			0
BUFFER_HEADER_LINKED_LIST_POS = 			1
BUFFER_HEADER_FRAME_NUM_POS	=   			2
BUFFER_HEADER_BUFFER_COUNT_POS =			3
BUFFER_HEADER_FRAME_BUFFER_COUNT_POS =  	4
BUFFER_HEADER_TIMESTAMP_POS	=   			5
BUFFER_HEADER_DATA_LENGTH_POS = 			6

In [61]:
# variables that you can adjust
correctDrive = False
f = open(driveName, "rb")  # Open drive

# Make sure this is the correct drive
# Read SD Card header and config sectors
f.seek(headerSector * sectorSize, 0)  # Move to correct sector
headerSectorData = np.fromstring(f.read(sectorSize), dtype=np.uint32)
if ((WRITE_KEY0 == headerSectorData[0]) and (WRITE_KEY1 == headerSectorData[1]) and (WRITE_KEY2 == headerSectorData[2]) and (WRITE_KEY3 == headerSectorData[3])):
    correctDrive = True
else:
    correctDrive = False
    f.close()

In [76]:
# Load up Config Sector
f.seek(configSector * sectorSize, 0)  # Move to correct sector
configSectorData = np.fromstring(f.read(sectorSize), dtype=np.uint8)

array([ 96,   2,   0,   0,  96,   2,   0,   0,  20,   0,   0,   0,   0,
       250,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [88]:
# Read Data Sectors
f.seek(dataStartSector * sectorSize, 0) # Starting data location
for i in range(20):
    dataHeaderLength = np.fromstring(f.read(4), dtype=np.uint32)
    dataHeader = np.fromstring(f.read((dataHeaderLength[0] - 1) * 4), dtype=np.uint32)
    print(dataHeader)
    data = np.fromstring(f.read((dataHeader[BUFFER_HEADER_DATA_LENGTH_POS - 1])), dtype=np.uint8)




[    0     0     0     0    57 63972]
[    1     0     1     1    61 63972]
[    2     0     2     2    65 63972]
[    3     0     3     3    70 63972]
[    4     0     4     4    74 63972]
[    0     0     5     5    77 63972]
[    1     1     6     0   107 63972]
[    2     1     7     1   111 63972]
[    3     1     8     2   116 63972]
[    4     1     9     3   120 63972]
[    0     1    10     4   124 63972]
[    1     1    11     5   128 63972]
[    2     2    12     0   158 63972]
[    3     2    13     1   162 63972]
[    4     2    14     2   166 63972]
[    0     2    15     3   171 63972]
[    1     2    16     4   175 63972]
[    2     2    17     5   178 63972]
[    3     3    18     0   208 63972]
[    4     3    19     1   213 63972]
